[package]
authors = ["Daniel Egger <daniel@eggers-club.de>"]
categories = [
    "embedded",
    "no-std",
]
description = "Firmware for my MCU power meter based upon STM32F042 and IN260"
documentation = "https://docs.rs/powermeter"
keywords = [
    "arm",
    "cortex-m",
    "template",
]
license = "0BSD"
name = "powermeter"
repository = "https://github.com/therealprof/powermeter"
version = "0.1.0"

[dependencies]
cortex-m = "0.5.8"
cortex-m-rt = "0.6.5"
ssd1306 = "0.2.1"
panic-halt = "0.2.0"
ina260 = "0.2.4"
embedded-graphics = "0.4.4"
heapless = "0.4.0"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.2"

[dependencies.stm32f042-hal]
features = ["rt"]
version = "0.6.5"

[dependencies.shared-bus]
features = ["cortexm"]
optional = false
version = "0.1.4"

[features]
default = ["rt"]
rt = []

[profile.dev]
debug = true

[profile.release]
debug = true
lto = true
opt-level = "s"
